FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /App

COPY *.csproj ./
RUN dotnet restore


COPY . ./
RUN dotnet publish -c Release -o out
COPY appsettings.json out/appsettings.json

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /App
COPY --from=build-env /App/out .
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://*:6001
ENV VIRTUAL_HOST=api.garyportal.tomk.online
ENV LETSENCRYPT_HOST=api.garyportal.tomk.online
ENTRYPOINT ["dotnet", "GaryPortalAPI.dll"]