name: GP-BUILDER

on:
  push:
    branches:
      - 'feature/v5features'

jobs:
  docker:
    name: Publish - Docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
            docker stop GPAPIDev 2>/dev/null || true
            docker rm GPAPIDev 2>/dev/null || true
            cp /home/GaryPortal/API/DEV/appsettings.Development.json appsettings.Development.json
            docker build -t garyportalapi-dev -f Dockerfile.dev .
            docker create -p 0.0.0.0:5000:5000 --name "GPAPIDev" --restart unless-stopped garyportalapi-dev
            docker start GPAPIDev
